--------------------------------------------------------
--  파일이 생성됨 - 수요일-11월-01-2023   
--------------------------------------------------------
-- USER 생성 및 권한 부여
-- USER SQL
CREATE USER "PROJECT" IDENTIFIED BY "1234"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "CONNECT" TO "PROJECT" ;
GRANT "RESOURCE" TO "PROJECT" ;
--------------------------------------------------------
-- SEQUENCE 생성
--------------------------------------------------------
--  DDL for Sequence CARTIDNUM
--------------------------------------------------------
   CREATE SEQUENCE  "PROJECT"."CARTIDNUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence QA_ID_SEQUENCE
--------------------------------------------------------
   CREATE SEQUENCE  "PROJECT"."QA_ID_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REVIEW_NUM
--------------------------------------------------------
   CREATE SEQUENCE  "PROJECT"."REVIEW_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
-- TABLE 생성
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------
  CREATE TABLE "PROJECT"."CART" 
   (	"CART_ID" NUMBER, 
	"MEMID" VARCHAR2(20 BYTE), 
	"PRODUCTCODE" VARCHAR2(50 BYTE), 
	"CNT" NUMBER DEFAULT 1, 
	"RDATE" DATE DEFAULT SYSDATE
   ) ;

   COMMENT ON COLUMN "PROJECT"."CART"."CART_ID" IS '장바구니 아이';
   COMMENT ON COLUMN "PROJECT"."CART"."MEMID" IS '회원아이디';
   COMMENT ON COLUMN "PROJECT"."CART"."PRODUCTCODE" IS '상품번호';
   COMMENT ON COLUMN "PROJECT"."CART"."CNT" IS '상품 수량';
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------
  CREATE TABLE "PROJECT"."CATEGORY" 
   (	"CATEGORY_CODE" NUMBER(10,0), 
	"MAIN_CATEGORY" VARCHAR2(50 BYTE), 
	"SUB_CATEGORY" VARCHAR2(50 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------
  CREATE TABLE "PROJECT"."MEMBER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(10 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(120 BYTE), 
	"REGDATE" VARCHAR2(20 BYTE) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
   ) ;
--------------------------------------------------------
--  DDL for Table ORDER_INFO
--------------------------------------------------------
  CREATE TABLE "PROJECT"."ORDER_INFO" 
   (	"ID" VARCHAR2(20 BYTE), 
	"ORDER_NUMBER" NUMBER(25,0), 
	"PAYMENT" VARCHAR2(30 BYTE), 
	"PRODUCT_CODE" VARCHAR2(20 BYTE), 
	"ORDER_COUNT" NUMBER(10,0), 
	"TOTAL_PRICE" NUMBER(20,0), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"PURCHASE_DATE" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------
  CREATE TABLE "PROJECT"."PRODUCT" 
   (	"PRODUCT_NAME" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(10,0), 
	"PRODUCT_CODE" VARCHAR2(20 BYTE), 
	"STOCK" VARCHAR2(10 BYTE), 
	"DETAIL" VARCHAR2(500 BYTE), 
	"SALE_COUNT" NUMBER(10,0) DEFAULT 0, 
	"CATEGORY_CODE" NUMBER(10,0), 
	"USE_YN" VARCHAR2(20 BYTE) DEFAULT 'Y'
   ) ;
--------------------------------------------------------
--  DDL for Table QA
--------------------------------------------------------
  CREATE TABLE "PROJECT"."QA" 
   (	"QA_ID" NUMBER, 
	"MEMID" VARCHAR2(20 BYTE), 
	"PRODUCTCODE" VARCHAR2(50 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"RDATE" DATE DEFAULT SYSDATE, 
	"CONTENT" VARCHAR2(500 BYTE), 
	"IMG" VARCHAR2(600 BYTE), 
	"PARENT_QA_ID" NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------
  CREATE TABLE "PROJECT"."REVIEW" 
   (	"ID" VARCHAR2(20 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"RECORD" NUMBER(10,0), 
	"PRODUCT_CODE" VARCHAR2(20 BYTE), 
	"REVIEW_NUM" NUMBER(10,0), 
	"REGDATE" DATE
   ) ;
--------------------------------------------------------
-- TABLE 에 DATA INSERT
--------------------------------------------------------
REM INSERTING into CART
SET DEFINE OFF;
Insert into "PROJECT".CART (CART_ID,MEMID,PRODUCTCODE,CNT,RDATE) values (53,'lee','100000011',1,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".CART (CART_ID,MEMID,PRODUCTCODE,CNT,RDATE) values (52,'lee','100000004',1,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".CART (CART_ID,MEMID,PRODUCTCODE,CNT,RDATE) values (54,'eee','200000062',2,to_date('2023/11/01','YYYY/MM/DD'));
REM INSERTING into CATEGORY
SET DEFINE OFF;
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (100,'고기/해산물/계란','돼지고기');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (100,'고기/해산물/계란','갑각류');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (100,'고기/해산물/계란','소고기');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (100,'고기/해산물/계란','닭고기');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (100,'고기/해산물/계란','계란');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (100,'고기/해산물/계란','조개류');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (100,'고기/해산물/계란','건어물');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (100,'고기/해산물/계란','기타 육류');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (100,'고기/해산물/계란','생선');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (200,'채소/과일','뿌리채소');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (200,'채소/과일','토마토');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (200,'채소/과일','과일');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (300,'간편식','밀키트');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (300,'간편식','라면');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (300,'간편식','시리얼');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (300,'간편식','반찬');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (300,'간편식','냉동식품');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (400,'간식','과자');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (400,'간식','베이커리');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (400,'간식','사탕/초콜릿/젤리');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (500,'음료','생수');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (500,'음료','탄산음료');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (500,'음료','과일음료');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (500,'음료','어린이음료');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (600,'유제품','우유');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (600,'유제품','두유');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (600,'유제품','요거트');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (600,'유제품','치즈');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (600,'유제품','버터/크림');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (700,'건강식품','비타민');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (700,'건강식품','유산균');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (700,'건강식품','다이어트');
Insert into "PROJECT".CATEGORY (CATEGORY_CODE,MAIN_CATEGORY,SUB_CATEGORY) values (700,'건강식품','영양식');
REM INSERTING into MEMBER
SET DEFINE OFF;
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('eee','1','양광진','010-1111-1111','rhkd@naver.com','서울시 강남구 화곡동 11-112','2023-10-27');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('admin','admin','관리자','010-1111-1111','admin@admin.com','서울시 강남구 역삼동 22-3','2023-10-27');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('hong','1','홍길동','010-1111-3333','hong@gmail.com','서울시 강남구 역삼동 33-2','2023-10-31');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('lee','2222','이씨','010-2222-2222','ee@test.com','서울시 강남구 신월동 33-3','2023-10-31');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('hong2','11','홍이동','010-2121-2121','hongee@gmail.com','서울시 강서구 방화동 22-2','2023-10-31');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('kang','11','강씨','010-1111-4444','kang@gmail.com','서울시 강남구 서초동 22-2','2023-10-31');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('qq','11','큐큐','010-9999-9999','qq@naver.com','서울시 마포구 망원2동 33-3','2023-10-31');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('ee','22','이이','010-2131-2112','ee@gmail.com','서울시 관악구 신림동 33-321','2023-10-31');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('e3','23','이삼','010-2323-2323','e3@test.com','서울시 강남구 역삼동 23-23','2023-10-31');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('eeee','1','1','010-1111-1111','2@2','서울시 강남구 d','2023-10-31');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('kim','1','김씨','010-1111-1111','kim@gmail.com','서울시 강남구 서초동 33-11','2023-10-31');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('44','44','사사','010-4444-4444','sa@sa.com','서울시 강남구 역삼동 4-4','2023-11-01');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('qwer','1','hong','010-1111-1111','test@test.com','서울시 강남구 집','2023-11-01');
Insert into "PROJECT".MEMBER (ID,PASSWORD,NAME,PHONE,EMAIL,ADDRESS,REGDATE) values ('dd','11','디디','010-2222-2222','dd@dd.com','서울시 관악구 봉천동 22-22','2023-11-01');
REM INSERTING into ORDER_INFO
SET DEFINE OFF;
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('PROJECT',20231026182837100000008,'체크/신용카드','100000008',5,16000,'주소',to_date('2023/10/26','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('PROJECT',20231026184918100000006,'무통장 입금','100000006',5,15000,'주소',to_date('2023/10/26','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('PROJECT',20231026185115100000006,'무통장 입금','100000006',5,15000,'주소',to_date('2023/10/26','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('PROJECT',20231026191406100000008,'휴대폰 간편결제','100000008',5,16000,'주소',to_date('2023/10/26','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('PROJECT',20231027175444200000001,'체크/신용카드','200000001',5,44500,'주소',to_date('2023/10/27','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('PROJECT',20231027180942200000001,'체크/신용카드','200000001',5,44500,'주소',to_date('2023/10/27','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231030162257100000004,'체크/신용카드','100000004',5,5000,'주소',to_date('2023/10/30','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231030164535100000010,'체크/신용카드','100000010',5,10000,'주소',to_date('2023/10/30','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231030170711100000010,'체크/신용카드','100000010',50,100000,'주소',to_date('2023/10/30','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('PROJECT',20231030182002100000010,'휴대폰 간편결제','100000010',5,10000,'주소',to_date('2023/10/30','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('PROJECT',20231030185613100000010,'휴대폰 간편결제','100000010',5,10000,'주소',to_date('2023/10/30','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('PROJECT',20231030203552100000015,'체크/신용카드','100000015',5,10000,'주소',to_date('2023/10/30','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('PROJECT',20231031094907100000016,'체크/신용카드','100000016',5,15000,'주소',to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('PROJECT',20231031095029100000016,'체크/신용카드','100000016',5,15000,'주소',to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('kim',20231031184445200000061,'체크/신용카드','200000061',5,1500,'주소',to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231031191639200000061,'체크/신용카드','200000061',1,300,'주소',to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231031191841100000005,'체크/신용카드','100000005',1,1500,'주소',to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231031153945200000061,'체크/신용카드','200000061',2,600,'주소',to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231031155031200000061,'체크/신용카드','200000061',5,1500,'주소',to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231031183057100000005,'체크/신용카드','100000005',1,1500,'주소',to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231031201722200000062,'체크/신용카드','200000062',1000,350000,'주소',to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231101115217100000005,'체크/신용카드','100000005',1,1500,'주소',to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('lee',20231101120655100000004,'체크/신용카드','100000004',1,1000,'주소',to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('admin',20231101122224100000004,'체크/신용카드','100000004',1,1000,'주소',to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('admin',20231101141615200000062,'체크/신용카드','200000062',1,350,'주소',to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231101145318200000065,'체크/신용카드','200000065',2,10000,'주소',to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231101145427200000062,'체크/신용카드','200000062',2,700,'주소',to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('admin',20231101160317200000061,'체크/신용카드','200000061',2,600,'주소',to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".ORDER_INFO (ID,ORDER_NUMBER,PAYMENT,PRODUCT_CODE,ORDER_COUNT,TOTAL_PRICE,ADDRESS,PURCHASE_DATE) values ('eee',20231101160612200000061,'체크/신용카드','200000061',2,600,'주소',to_date('2023/11/01','YYYY/MM/DD'));
REM INSERTING into PRODUCT
SET DEFINE OFF;
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('방울토마토',8900,'200000001','40','대추방울토마토',40,200,'N');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('라면',2000,'300000002','100','라면',5,300,'N');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('사이다',2000,'500000003','100','사이다',3,500,'N');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('계란10구',1000,'100000004','100','계란10구',12,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('계란15구',1500,'100000005','500','계란15구',10,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('계란30구',3000,'100000006','500','계란30구',10,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('구운계란1',1200,'100000007','100','구운계란1',3,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('구운계란30구',3200,'100000008','90','구운계란30구',10,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('닭고기',2000,'100000009','100','닭볶음탕용',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('닭고기',2000,'100000010','50','닭가슴살',115,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('닭고기',2000,'100000011','100','닭다리살',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('닭고기',2000,'100000012','100','닭안심살',3,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('닭고기',2000,'100000013','100','윙',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('닭고기',2000,'100000014','100','윙봉',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('닭고기',2000,'100000015','95','백숙용',5,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('돼지고기',3000,'100000016','90','고추장불고기',10,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('돼지고기',3000,'100000017','100','냉동삼겹살',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('돼지고기',3000,'100000018','100','대페',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('돼지고기',3000,'100000019','100','등갈비',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('돼지고기',3000,'100000020','100','목살',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('돼지고기',3000,'100000021','100','벌집삼겹살',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('돼지고기',3000,'100000022','100','삼겹살',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('돼지고기',3000,'100000023','100','수육용',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('돼지고기',3000,'100000024','100','제주흑돼지앞다리',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('돼지고기',3000,'100000025','100','항정살',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('반숙계란10구',1200,'100000026','100','반숙계란10구',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',3000,'100000027','100','수입LA갈비',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',3000,'100000028','100','수입국거리',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',3000,'100000029','100','수입부채살',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',3000,'100000030','110','수입살치살',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',3200,'100000031','105','수입우삼겹',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',3000,'100000032','105','수입척아이롤',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',3000,'100000033','100','한우다짐육',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',4000,'100000034','55','한우등심',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',4500,'100000035','100','한우사골',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',4500,'100000036','78','한우양지국거리',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',4500,'100000037','57','한우차돌박이',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('소고기',4500,'100000038','87','한우치마살',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('가리비',3000,'100000039','100','가리비',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('갈치',3000,'100000040','50','갈치',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('고등어',3000,'100000041','40','고등어',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('꼬막',3000,'100000042','40','꼬막',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('꽃게',3000,'100000043','100','꽃게',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('낙지',3000,'100000044','50','낙지',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('명태포',3000,'100000045','100','명태포',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('모시조개',3000,'100000046','100','모시조개',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('바지락',3000,'100000047','45','바지락',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('백합',3000,'100000048','100','백합',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('보리새우',3000,'100000049','100','보리새우',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('삼치',3000,'100000050','100','삼치',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('새우',2500,'100000051','100','새우',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('아귀포',3000,'100000052','100','아귀포',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('오징어',2000,'100000053','100','오징어',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('오징어채',2000,'100000054','100','오징어채',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('왕오징어구이',2500,'100000055','100','왕오징어구이',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('쥐포',2000,'100000056','100','쥐포',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('쭈꾸미',2500,'100000057','78','쭈꾸미',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('홍합',2500,'100000058','65','홍합',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('유정란15구',1500,'100000059','100','유정란15구',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('하얀계란30구',3000,'100000060','100','하얀계란30구',0,100,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('감자',300,'200000061','983','감자100g당 금액',117,200,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('고구마',350,'200000062','997','고구마100g당 금액',1129,200,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('단호박',300,'200000063','100','단호박100g당 가격',134,200,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('당근',350,'200000064','150','당근100g당 가격',132,200,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('산마',5000,'200000065','998','수정합니다아',55,200,'Y');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('만가닥버섯',300,'200000066','100','만가닥버섯',13,200,'N');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('콜라',1000,'500000069','100',null,0,500,'N');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('햇반',3000,'300000068','0',null,0,300,'N');
Insert into "PROJECT".PRODUCT (PRODUCT_NAME,PRICE,PRODUCT_CODE,STOCK,DETAIL,SALE_COUNT,CATEGORY_CODE,USE_YN) values ('신라면',1500,'400000070','50','매워요',0,400,'Y');
REM INSERTING into QA
SET DEFINE OFF;
Insert into "PROJECT".QA (QA_ID,MEMID,PRODUCTCODE,CATEGORY,TITLE,RDATE,CONTENT,IMG,PARENT_QA_ID) values (28,'eee',null,'환불 문의','ㅇㅇㅇ',to_date('2023/11/01','YYYY/MM/DD'),'ㅇㅇㅇㅇ',null,0);
Insert into "PROJECT".QA (QA_ID,MEMID,PRODUCTCODE,CATEGORY,TITLE,RDATE,CONTENT,IMG,PARENT_QA_ID) values (29,'eee',null,'환불 문의','ㅇㅇㅇ',to_date('2023/11/01','YYYY/MM/DD'),'ㅇㅇㅇㅇ',null,0);
Insert into "PROJECT".QA (QA_ID,MEMID,PRODUCTCODE,CATEGORY,TITLE,RDATE,CONTENT,IMG,PARENT_QA_ID) values (31,'admin',null,null,'관리자답변',to_date('2023/11/01','YYYY/MM/DD'),'ㄹㄹ',null,30);
Insert into "PROJECT".QA (QA_ID,MEMID,PRODUCTCODE,CATEGORY,TITLE,RDATE,CONTENT,IMG,PARENT_QA_ID) values (30,'eee',null,'상품 문의','토마토',to_date('2023/11/01','YYYY/MM/DD'),'맛이 좋나요',null,0);
Insert into "PROJECT".QA (QA_ID,MEMID,PRODUCTCODE,CATEGORY,TITLE,RDATE,CONTENT,IMG,PARENT_QA_ID) values (33,'admin',null,null,'관리자답변',to_date('2023/11/01','YYYY/MM/DD'),'출발했어요',null,32);
Insert into "PROJECT".QA (QA_ID,MEMID,PRODUCTCODE,CATEGORY,TITLE,RDATE,CONTENT,IMG,PARENT_QA_ID) values (32,'eee',null,'배송 문의','배송',to_date('2023/11/01','YYYY/MM/DD'),'언제오나요',null,0);
Insert into "PROJECT".QA (QA_ID,MEMID,PRODUCTCODE,CATEGORY,TITLE,RDATE,CONTENT,IMG,PARENT_QA_ID) values (36,'admin',null,null,'관리자답변',to_date('2023/11/01','YYYY/MM/DD'),'배송이 시작되기 전 취소하는 경우 전액 환불됩니다.
            그러나 배송이 시작된 이후에는 환불 비용 5000원을 제외한 금액만 환불 계좌로 입금됩니다.
            상품을 회수하고 검수하는 과정에서 1~2일 소요되며, 검수가 완료되면 환불처리 됩니다.
            환불은 카드사에 따라 다르나 평균 영업일 기준 5일 소요될 수 있습니다.',null,35);
Insert into "PROJECT".QA (QA_ID,MEMID,PRODUCTCODE,CATEGORY,TITLE,RDATE,CONTENT,IMG,PARENT_QA_ID) values (34,'eee',null,'상품 문의','테스트',to_date('2023/11/01','YYYY/MM/DD'),'테스',null,0);
Insert into "PROJECT".QA (QA_ID,MEMID,PRODUCTCODE,CATEGORY,TITLE,RDATE,CONTENT,IMG,PARENT_QA_ID) values (35,'eee',null,'환불 문의','환불 규정에 대해 알고싶어요 ',to_date('2023/11/01','YYYY/MM/DD'),'알려주세요',null,0);
REM INSERTING into REVIEW
SET DEFINE OFF;
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('kim','방울토마토맛있음',9,'200000001',null,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('KIM','수정이 되면 안되;자나요',1,'200000001',1,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('KIM','ㅇㅇㅇㅇㅇㅇㄷ',4,null,2,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'ddd',3,null,13,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,null,1,null,4,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'안녕하세요',55,null,5,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'수정
ㅇㅇㅇㅇㅇㅇ',9,null,14,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'ㅇㅇ',9,null,7,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'수정을 하겠슨니다',5,null,8,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'참치마요
전주비빔',7,null,9,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'안녕',5,null,18,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'dddd',1,null,11,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'리뷰 입력하기기기기ㅣ긱',5,null,25,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'ㅎㅎ',2,null,15,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'ffff',1,null,16,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'ffff',1,null,26,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'ddd',9,null,21,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'jjjjjjjjjjjjjjjjjjjjjjjj',8,null,22,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'jjjjjjjjjjjjjjjjjjjjjjjj',8,null,23,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'ㅇㅇㅇㅇ',4,null,24,null);
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'리뷰 입력합니다아ㅏㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ',6,null,27,to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'매퍼새로적용한 리뷰입니다',7,null,28,to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'ffff',6,null,29,to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'ddddddd',6,null,30,to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'ddddddd',6,null,31,to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'eeeeeeeeeeee',1,null,32,to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'dfdddd',4,null,33,to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee',' 안녕ㄷㅣ지몬',7,null,34,to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','dasd',1,null,35,to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','dasd',1,null,36,to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','감자',4,null,37,to_date('2023/10/31','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','이건뭐죠',6,null,38,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','ffffffffff',2,null,39,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','오ㅐ 안되세요??',5,null,40,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','qwer',7,null,41,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','qwer',7,null,42,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','qwer',1,null,43,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','제발 전송되라',3,null,44,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','지금은>',4,null,45,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','어ㅏㄴㄴㅇㅇㅇ',3,null,46,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'tnwjdjdjdjkdddddddd',3,'null',54,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values (null,'fff',4,'null',48,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','ㅇㅇㅇㅇ',4,'200000061',49,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','dddddddddddddddd',1,'200000061',50,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','맛 좋아용',1,'200000061',55,to_date('2023/11/01','YYYY/MM/DD'));
Insert into "PROJECT".REVIEW (ID,CONTENT,RECORD,PRODUCT_CODE,REVIEW_NUM,REGDATE) values ('eee','ㅇㅇㅇㅇㅇ',9,'200000063',52,to_date('2023/11/01','YYYY/MM/DD'));
--------------------------------------------------------
-- TABLE 제약 조건 부여
--  DDL for Index CART_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX "CART_PK" ON "PROJECT"."CART" ("CART_ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007227
--------------------------------------------------------
  CREATE UNIQUE INDEX "SYS_C007227" ON "PROJECT"."MEMBER" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007178
--------------------------------------------------------
  CREATE UNIQUE INDEX "SYS_C007178" ON "PROJECT"."ORDER_INFO" ("ORDER_NUMBER") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007176
--------------------------------------------------------
  CREATE UNIQUE INDEX "SYS_C007176" ON "PROJECT"."PRODUCT" ("PRODUCT_CODE") 
  ;
--------------------------------------------------------
--  DDL for Index QUESTION_PK
--------------------------------------------------------
  CREATE UNIQUE INDEX "QUESTION_PK" ON "PROJECT"."QA" ("QA_ID") 
  ;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------
  ALTER TABLE "PROJECT"."CART" ADD CONSTRAINT "CART_PK" PRIMARY KEY ("CART_ID") ENABLE;
  ALTER TABLE "PROJECT"."CART" MODIFY ("PRODUCTCODE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CART" MODIFY ("MEMID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."CART" MODIFY ("CART_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------
  ALTER TABLE "PROJECT"."CATEGORY" MODIFY ("CATEGORY_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------
  ALTER TABLE "PROJECT"."MEMBER" ADD PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_INFO
--------------------------------------------------------
  ALTER TABLE "PROJECT"."ORDER_INFO" ADD PRIMARY KEY ("ORDER_NUMBER") ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------
  ALTER TABLE "PROJECT"."PRODUCT" MODIFY ("CATEGORY_CODE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."PRODUCT" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."PRODUCT" ADD PRIMARY KEY ("PRODUCT_CODE") ENABLE;
--------------------------------------------------------
--  Constraints for Table QA
--------------------------------------------------------
  ALTER TABLE "PROJECT"."QA" ADD CONSTRAINT "QUESTION_PK" PRIMARY KEY ("QA_ID") ENABLE;
  ALTER TABLE "PROJECT"."QA" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."QA" MODIFY ("MEMID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."QA" MODIFY ("QA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ORDER_INFO
--------------------------------------------------------
  ALTER TABLE "PROJECT"."ORDER_INFO" ADD CONSTRAINT "PC_CODE2" FOREIGN KEY ("PRODUCT_CODE")
	  REFERENCES "PROJECT"."PRODUCT" ("PRODUCT_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------
  ALTER TABLE "PROJECT"."REVIEW" ADD CONSTRAINT "PC_FK" FOREIGN KEY ("PRODUCT_CODE")
	  REFERENCES "PROJECT"."PRODUCT" ("PRODUCT_CODE") DISABLE;
